### PR TITLE
fixed navigating user profiles

### LINKED ISSUE #84: Fix navigation of User Profiles

### PR DESCRIPTION
**Pull request by jas-haria**

### CODE REVIEW

File: frontend/src/Components/CustomNavbar.tsx [hunk 1]
```diff
@@ -8,7 +8,10 @@ import { useNavigate } from 'react-router-dom';
 
 
 function CustomNavbar() {
-  const [permission, editPermission] = useState<String>("Employee");
+  if (null == localStorage.getItem("Permission")) {
+    localStorage.setItem("Permission", "Employee")
+  }
+  const [permission, editPermission] = useState<String>(localStorage.getItem("Permission") || "Employee");
```
Comment (AugustusSaalfeldCMU) [inline frontend/src/Components/CustomNavbar.tsx:14]: is || "Employee" necessary since Permission should never be null at this point bc of line 11 and 12?

Comment (jas-haria) [reply frontend/src/Components/CustomNavbar.tsx:14]: Yes it is as localStorage.getItem returns String or Null datatype. Even if logically it will not be Null, conceptually it can be
